# JEH Real-ESRGAN Docker compose.yaml
# v1.0 2021-09-30

services:
  app:
    container_name: esrgan # Specify the custom container name
    build:
      context: .
      dockerfile: Dockerfile
    image: real-esrgan:1.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    volumes:
      - ./sync:/home/dockeruser/sync  # Mount the local `./sync` directory to `~/sync/` in the container
    stdin_open: true            # Keep stdin open for interactive shell
    tty: true                   # Allocate a pseudo-TTY for the container
    restart: always